---
name: vscode-solidity-server
description: Solidity language server.
homepage: https://github.com/juanfranblanco/vscode-solidity
licenses:
  - MIT
languages:
  - Solidity
categories:
  - LSP

source:
  id: pkg:github/juanfranblanco/vscode-solidity@master
  build:
    run: |
      npm ci
      npm run build:cli

bin:
  vscode-solidity-server: node:dist/cli/server.js
